[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "a605f0880b05ab9e5b12a753dc38d2db0a64322d6031c38e4e5243adf2d0cf3b"
[auth.google]
client_id = "143940890426-ujorlor2ficn1ifj6i4i9mdjjjj342o1.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"